{% set name = "mesa-geo" %}
{% set version = "0.6.0" %}
package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://github.com/projectmesa/mesa-geo/archive/v{{ version }}.tar.gz
  sha256: 67a932380fc0ae8c5c31b7d6038fec9918c7883d22202c06820cbb128b423ee6
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - mesa >=2.1.0,<2.2.dev0
    - pip
  run:
    - python >=3.8
    - mesa >=2.1.0,<2.2.dev0
    - geopandas
    - libpysal
    - rtree
    - rasterio
    - shapely
    - numpy
    - pyproj
    - folium
    - xyzservices >=2022.9.0
test:
  imports:
    - mesa_geo
  commands:
    - pip check
  requires:
    - pip
about:
  home: https://github.com/projectmesa/mesa-geo
  license: Apache-2.0
  license_file: LICENSE
  summary: "GIS Extension for Mesa Agent-Based Modeling"
  description: "Mesa-Geo implements a GeoSpace that can
  host GIS-based GeoAgents, which are like normal Agents, 
  except they have a geometry attribute that is a Shapely object and a crs attribute for 
  its Coordinate Reference System. You can use Shapely directly to create arbitrary geometries, but in most cases you will want to import your geometries from a file. 
  Mesa-Geo allows you to create GeoAgents from any vector data file (e.g. shapefiles), valid GeoJSON objects or a GeoPandas GeoDataFrame."
extra:
  recipe-maintainers:
    - adamamer20
